### ISSUE TITLE
"Open Unblank" setting?

### ISSUE THREAD

**Issue by porjo** [sunwxg/gnome-shell-extension-unblank#14]
Could someone clarify what the toggle switch 'Open Unblank' does? The extension doesn't work for me unless this is in the on position (i.e. with this off, the screen goes blank upon lock). If I want to enable/disable the extension I will turn it on/off from the Gnome extensions manager...not within the extension itself. This is confusing. Thanks.

**Comment by sunwxg** [comment]
If you want to disable this extension, you'd better delete the extension.
The reason is a bit complex, I don't want to explain here.

**Comment by porjo** [comment]
That's fine. I don't mean to complain - I really appreciate your efforts! Perhaps that option could be named 'Enable Unblank' and turning it off causes other options to be greyed out (i.e. not selectable)? (just to be clear what it does)

**Comment by sunwxg** [comment]
Thanks for your suggestion. I'll improve it.
