### ISSUE TITLE
Only unblank on main power

### ISSUE THREAD

**Issue by curvatura99** [sunwxg/gnome-shell-extension-unblank#15]
The behavior for this option is as follows when enabled on my Lenovo 320 ideapad:

Pull the power cord, verify laptop is in powersave mode, then lock the screen. The lock screen comes down and the screen does not go blank.

Lock the screen, verify laptop is in powersave mode via ssh, then pull the power cord. Screen goes blank. Pressing any key or using the touchpad does nothing to make the screen re-appear. Only after reconnecting the power cord does the lock screen re-appear.

I'm pretty sure this is not the intended behavior.

**Comment by sunwxg** [comment]
Thank you, I will work on it.

**Comment by curvatura99** [comment]
谢谢 - I know you'll make the extension even better.

**Comment by sunwxg** [comment]
I updated the repo, could you do a test?

**Comment by curvatura99** [comment]
With the update if you pull the power cord and lock the screen it goes blank. However if you lock the screen and then pull the power cord the screen does not go blank. Unsure how you want the behavior, but at least now when you lock the screen on battery the screen does go blank.

**Comment by curvatura99** [comment]
I have more information. When you lock the screen and then pull the power cord the screen does not blank, however the screen will blank eventually based on the power settings. I can now say your update was success. Thank you so much.

**Comment by sunwxg** [comment]
Thanks!
Closed.

**Comment by curvatura99** [comment]
Just to let you know the extension from the master works with battery power. However the recent update at extensions.gnome.org is using the previous code in prefs.js and extension.js, so of course it doesn't work. Are you doing some more testing before releasing? Thanks.

**Comment by sunwxg** [comment]
I will send the latest code to extensions.gnome.org.

**Comment by curvatura99** [comment]
I appreciate all the work you're doing. Thanks again.
