### ISSUE TITLE
Confusion with setting titles

### ISSUE THREAD

**Issue by engineer22** [sunwxg/gnome-shell-extension-unblank#20]
I believe the settings need a re-write for better understanding. I had hard time understanding after installing via the GNOME Software app.

I propose to change:

1. "Open Unblank" to "Enable Unblank"
2. "Only unblank when on mains power" to "Only unblank when on AC"
3. "Close monitor delay" to "Timeout after closing monitor/lid for"

I like this extension and I think these changes will help new users.

- Debian 10
- GNOME 3.30.2
- Installed via the GNOME Software application

**Comment by sunwxg** [comment]
> 1. "Open Unblank" to "Enable Unblank"
> 2. "Only unblank when on mains power" to "Only unblank when on AC"
These two will be fixed.

> 3. "Close monitor delay" to "Timeout after closing monitor/lid for"
I think it's "Timeout to blank after locking the screen".

**Comment by engineer22** [comment]
Sounds great @sunwxg!
