### ISSUE TITLE
Screen blanks after 30 minutes in lock screen regardless of settings

### ISSUE THREAD

**Issue by bridgesense** [sunwxg/gnome-shell-extension-unblank#22]
on  Redhat 8.3
xset -q doesn't show any additional settings
dpms extensions are not loaded

The extension prevents screen blanking and displays the lock screen.  Unfortunately, after 30 minutes the lock screen eventually blanks anyway.  I don't see any settings pertaining to this and am wondering if this is fired during the blank event itself?  Any ideas?

I use this extension to keep secondary monitor from going blank as most of the time it never comes back on when waking or locks up the system.

**Comment by sunwxg** [comment]
Show the value:
```
gsettings --schemadir ~/.local/share/gnome-shell/extensions/unblank@sun.wxg@gmail.com/schemas get org.gnome.shell.extensions.unblank time
```

**Comment by bridgesense** [comment]
It shows zero:

0

**Comment by bridgesense** [comment]
Yeah, 30 minutes after the lock mode is initiated, another blank event is fired from somewhere.  While in lock mode, the extension doesn't catch the blank event to supersede.   Actually, I don't think gnome extensions can work within the lock screen environment, do they?

**Comment by sunwxg** [comment]
The extension can work when screen is locked, but need some tricks.
I don't know what happened on your system.

**Comment by bridgesense** [comment]
If I discover anything, I'll pass it on.. otherwise this looks like a local issue and nothing to do with extension.  Thanks!

**Comment by bridgesense** [comment]
I'm not experiencing an issue any longer.  I'm closing this.  Thanks!
