### ISSUE TITLE
Lock screen time not displayed correctly or "cut-off"

### ISSUE THREAD

**Issue by LeFloatyPancake** [sunwxg/gnome-shell-extension-unblank#24]
Gnome 40

After a set amount of time in the lock screen, the last digit of the digital clock is either cut-off or not displayed correctly. I discovered that this behavior is triggered after going beyond the set timeout specified in `gnome settings>power>power saving>blank screen timeout` but its not always the case (sooo I have no clue as to what the root cause is).

![test2](https://user-images.githubusercontent.com/83509112/121179370-43034400-c892-11eb-8338-8bc342494c1c.jpg)
![test1](https://user-images.githubusercontent.com/83509112/121179379-45fe3480-c892-11eb-82c0-7dbe94405a8c.jpg)

I already tried: 
1. Disabling all other extensions plus a restart (just to be sure)
2. Changing font styles in gnome tweaks

**Comment by sunwxg** [comment]
I believe this issue has no relation with this extension.
If you want to make sure it, you can try to create a new user and login as new user, only install this extension, then do the test.

**Comment by LeFloatyPancake** [comment]
Followed your suggestion so I set up a fresh install of fedora in a VM. You're right there must be something in my config that causes this. Thanks.
