### ISSUE TITLE
Support gnome shell version 44

### ISSUE THREAD

**Issue by aggstam** [sunwxg/gnome-shell-extension-unblank#29]
Based on commits f883f6845c5c927e58b7b0b999555862fe8f4df1 and d3a9f70b0772783c096fe708e0deac39c19efc8f to support gnome shell version 44 a simple inclusion of "44" to that array should suffice.
I don't think a PR is needed for such a small addition, but let me know if further testing is required.

**Comment by sunwxg** [comment]
I will test it on GNOME 44 these days.
Thank you.

**Comment by aggstam** [comment]
Updated today and verifying it works on GNOME 44.
Closing this issue as solved.
Thanks a lot!
