### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by corebots** [sunwxg/gnome-shell-extension-unblank#3]
thank you for this nice functionality. please could you add a timer like to blank the screen after an hour after the screenshield has been activated?

**Comment by dtmland** [comment]
+1

> thank you for this nice functionality. please could you add a timer like to blank the screen after an hour after the screenshield has been activated?

**Comment by sunwxg** [comment]
The timer function has been added. The new version is waiting for review at extensions.gnome.org . If you want to try it now, you can clone my repo, and install it manually.

**Comment by szpak** [comment]
@sunwxg Thanks for the new feature. I gave it a try and it works somehow weird. For 30 minutes it waits about 60 seconds, for 60 minutes ~90s. Looking at the Gnome [documentation](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-timeout-add) it seems that values are provided in milliseconds, so in addition to `* 1000` you would need to add `* 60`. The documentation also mentions [timeout-add-seconds](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-timeout-add-seconds) - maybe it would be better?
I wanted to fix it quickly, but it behaved not as I expected. I'm not a Gnome or JavaScript developer and probably I missed something.

**Comment by sunwxg** [comment]
Thank you! That's my fault, I have updated, you can try again.

**Comment by szpak** [comment]
I did that change previously, but it didn't work as I expected. E.g. `timebox_comboBox.append("60", "1 minute");` causes delay around 85-90 seconds. I didn't have enough patience to test 30 minutes :).

**Comment by szpak** [comment]
Maybe that timer is just not precise enough as the documentation mentioned...

**Comment by dtmland** [comment]
After sorting through the time offset, it looks like the feature works exactly as expected. Thanks!

Gnome tweak tool provides a nice GUI interface to enable the extension - perhaps eventually a field could be added that controls the timeout.

Either way this extension is a savior for gnome. It's surprising these options are not already built into gnome. I get the impression that when developers of the gnome lock screen shield decided to create an interface that would work great for a tablet they completely forgot that desktop interfaces exist.

**Comment by szpak** [comment]
Yes, I have been subscribed to the related thread in Bugzilla for years... Thanks for maintaining that plugin!

**Comment by LoneFenris** [comment]
I think this function may have broken in GNOME Shell 3.36? It doesn't seem to blank after any amount of time anymore.

**Comment by sunwxg** [comment]
I updated the code, could you test it?

**Comment by LoneFenris** [comment]
It does blank now (though it might be a few minutes late, I can't tell). 

However, it will not unblank in response to mouse or keyboard activity. I even unlocked it without the monitor coming back on. In order to get it to unblank, I had to change to a tty and back -- after which point, the extension would not blank the monitor again until I logged out and back in.

**Comment by LoneFenris** [comment]
It does seem to be about 10 minutes late to blank on the 30-minute timer. That is, it blanks after 40 minutes with the timer set to 30 minutes. Not super-important, I suppose, though.

**Comment by sunwxg** [comment]
Updated. Please test it again.
I haven't the environment to test it now. Thank you for your testing.

**Comment by LoneFenris** [comment]
No change in behavior.
