### ISSUE TITLE
Screen goes blank after 30 seconds of idle time after resume from suspend

### ISSUE THREAD

**Issue by TellThatToLuke** [sunwxg/gnome-shell-extension-unblank#34]
### Introduction
I initially thought this was a bug with the [Gnome Settings Daemon](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/809), but after disabling this extension, the issue has not persisted.

### Bug Summary
When I restart my laptop and start a GNOME session, the screen dims after 2 minutes and 30 seconds of idle time. Then, when I suspend my laptop and resume from suspend, unlocking GDM to enter the GNOME session, the screen goes blank after 30 seconds of idle time.

### Affected Version
- Gnome Shell 46

**Comment by sunwxg** [comment]
> When I restart my laptop and start a GNOME session, the screen dims after 2 minutes and 30 seconds of idle time.

Is this the right or wrong behavior?

> Then, when I suspend my laptop and resume from suspend, unlocking GDM to enter the GNOME session, the screen goes blank after 30 seconds of idle time.

**Comment by TellThatToLuke** [comment]
Screen dimming after 2 minutes and 30 seconds of idle time is right behavior. Screen blanking after 30 seconds is the wrong behavior.

**Comment by sunwxg** [comment]
This extension is to unblank the screen when screen locked. Why did your screen dim? That means this extension didn't work well.

**Comment by TellThatToLuke** [comment]
The extension works as intended on the lock screen. However, the wrong behaviour of the screen going blank after 30 seconds occurs when resuming from suspend and logging into the GNOME session. As mentioned, this issue has not persisted since disabling the extension.

**Comment by sunwxg** [comment]
2 minutes and 30 seconds is the time you defined to lock the screen, where does you set it?

**Comment by TellThatToLuke** [comment]
I think it is half the duration of the screen blank setting.
![image](https://github.com/user-attachments/assets/63a78f88-dbad-4be5-972d-45f8b031a9ea)

**Comment by sunwxg** [comment]
The right time is 5 minutes, why is it the half of 5 minutes? There is some special settings on your system.

**Comment by sunwxg** [comment]
You can try to disable `Dim Screen` in Power Saving.

**Comment by TellThatToLuke** [comment]
Why would I do that? The screen dimming after 2 minutes and 30 seconds of idle time is normal for my settings. However, when I enable this extension, the screen blanks after 30 seconds of idle time upon resuming from suspend in the GNOME session, which is not in line with my settings.

**Comment by TellThatToLuke** [comment]
I no longer require this extension, but I was unable to find a resolution for the issue. I will be closing the ticket, but you are welcome to reopen it if needed.
