### ISSUE TITLE
Keep "dimming efect" on screen lock

### ISSUE THREAD

**Issue by szpak** [sunwxg/gnome-shell-extension-unblank#5]
Gnome by default starts "dimming" a screen a few seconds before locking a screen. It's nice, as you can react (e.g. pressing a CTRL key) before the screen/computer is effectively lock out. Having your extension enabled a screen is immediately locked out.

It would be nice to be able to keep that effect when unblank is enabled (if possible to reconcile).

**Comment by sunwxg** [comment]
I updated the repo to enable dimming screen function. You can try it.

**Comment by szpak** [comment]
Thanks for your quick action!

I gave it a try and it looks ok in the basic use case. However, I've found one caveat.

### Steps to reproduce:
1. Wait until a screen starts dimming.
2. Interrupt the process (by hitting a CTRL key or moving a mouse)

### Actual result:
The dimming action is interrupted, but after several seconds the monitor is blanked. What's worse, when I unblank the screen I'm not asked for a password to unlock my computer.
It seems that locking a screen is interrupted, but disabling of a screen is not.

### Expected result:
Inactivity timer is restarted and I have to wait another X minutes to have my "screen" locked.

**Comment by sunwxg** [comment]
You means only the first time dimming screen after system starts you meet the problem. After the first time dimming screen, you  will not meet the problem. Is that correct?

I can't produce your fault on my system. My gnome is 3.30.

**Comment by szpak** [comment]
It just updated the extension and restarted gnome-shell. It happens every time (at least a few times I tested). How long have you been waiting for the effect? I tested it with a delay time set to 5 minutes and I needed to wait several seconds.

I will restart my computer and check it.

I have Fedora 29 with gnome-shell-3.30.2-1.fc29.x86_64.

**Comment by sunwxg** [comment]
I set idle-delay time to 1 minuties and after dimming starts, wait about 5 seconds, I interrupt dimming.

Your GNOME works on X or wayland?

**Comment by sunwxg** [comment]
I test it on wayland again, don't meet problem.

**Comment by szpak** [comment]
It's on X. I'm still [waiting](https://gitlab.gnome.org/GNOME/mutter/merge_requests/320) for a clipboard manager in GNOME on Wayland...

Please wait 20+ seconds after interrupting dimming.

**Comment by sunwxg** [comment]
After interrupting dimming I wait more than 20 seconds, until next dimming starts, I don't meet problem.

**Comment by szpak** [comment]
After restart I changed power settings to one minute and I wasn't encounter the problem. I switched back to 5 minutes (and still 5 minutes in your plugin) and it again I wasn't able to reproduce the problem. I don't know why restart could "fix" it. I will observe it and get back to you if happened again.

Sorry for providing a not very reproducible problem :/

**Comment by szpak** [comment]
Just FYI. It still happens occasionally on my machine. However, maybe I the only one affected, so I propose to just wait for a report from another person.

**Comment by szpak** [comment]
After upgrade to Gnome 3.36 (and the plugin update to master) I no longer observe the [aforementioned problem](https://github.com/sunwxg/gnome-shell-extension-unblank/issues/5#issuecomment-475953266) :).

Closing as the original feature has been implemented long time ago :).
