### ISSUE TITLE
Extension takes a long time to initialize

### ISSUE THREAD

**Issue by LoneFenris** [sunwxg/gnome-shell-extension-unblank#6]
I've noticed that the extension takes a long time to initialize (either on login or on enable). During the initialization time, the system may appear frozen (on login, the screen even blanks until gnome shell finishes loading in). Any idea what would be causing such a long initialization time?

**Comment by sunwxg** [comment]
Which gnome version do you work on?

**Comment by LoneFenris** [comment]
Arch Linux. `gnome-shell --version` shows 3.32.2. The package version is `gnome-shell 1:3.32.2+1+g24cb1c1aa-1`

**Comment by sunwxg** [comment]
Okay, I will check it.

**Comment by sunwxg** [comment]
I updated the code. You can try the new code.

**Comment by LoneFenris** [comment]
Initialization seems to be quick now, with the side effect that locking the screen takes a longer time. But I suppose that might be a less likely time for people to notice. Don't know why that call seems to take so long, though.

I did have some trouble once, trying to unlock the screen after it had blanked from the extension's timeout. It only happened once so far, so it may have been an unrelated or isolated glitch.

**Comment by sunwxg** [comment]
I updated code, could you try again?

>I did have some trouble once, trying to unlock the screen after it had blanked from the extension's timeout. It only happened once so far, so it may have been an unrelated or isolated glitch.

I think that is a different issue.

**Comment by LoneFenris** [comment]
Back to the earlier behavior of having a long initialization time.

**Comment by sunwxg** [comment]
I updated the code again. Could you try the new solution.

**Comment by LoneFenris** [comment]
Seems to be working better. No noticeable hang on login or lock. I'm curious, was the latest change to basically add a null callback to the call for the proxy?

**Comment by sunwxg** [comment]
Thanks for your testing.

Adding a null callback can make `new DisplayConfigProxy` to work async. If you want to know detail information, you can search `makeProxyWrapper` in gjs source code.

**Comment by LoneFenris** [comment]
Interesting. I had thought simply having both Initable and AsyncInitable interfaces implemented was enough to make init async. Good to know. Thanks.
